language: php
matrix:
  include:
    - php: 5.6
    - php: 5.5
before_install:
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git
  - cd neos-base-distribution
  - composer require flowpack/elasticsearch-contentrepositoryadaptor dev-master
install:
  - composer install
script:
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Flowpack.ElasticSearch.ContentRepositoryAdaptor/Tests/Unit